---
download_packages_aur:
  - slack-desktop
  - spotify
  - golangci-lint
  - nerdfetch
  - zen-browser-bin
  - localsend-bin

download_packages_base:
  - fzf
  - bat
  - neovim
  - eza
  - glow
  - htop
  - jq
  - yq
  - nodejs
  - pyenv
  - ripgrep
  - tmux
  - stow
  - tree
  - go
  - wget
  - zsh
  - kitty
  - kubectl
  - kubectx
  - shellcheck
  - gum
  - starship
  - lazygit
  - presenterm
  - btop

download_packages_homebrew_cask:
  - docker
  - silicon
  - spotify
  - font-jetbrains-mono-nerd-font
  - ghostty
  - zen-browser
  - localsend

download_packages_linux:
  - firefox
  - docker
  - silicon
  - notion
  - github-cli
  - redshift
  - ghostty
  - spotify-launcher
  - wl-clipboard
  # for bluetooth widget in qtile
  - python-dbus-next
  - bluez
  - bluez-utils
# ---------

download_packages_mac:
  - karabiner-elements
  - raycast
  - whatsapp
  - awscli
  - ansible-lint
  - gh
  - golangci-lint
  - nerdfetch
  - colima
